import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Container } from '@repo/ui/custom_components/container';
import Header from './components/header';
import NewHeader from './components/new-header';
import Footer from './components/footer';

// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
// });
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   variable: '--font-geist-mono',
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, height=device-height, initial-scale=1.0"
        />
      </head>
      <body>
        <NewHeader />
        <main className="pt-[var(--navigation-height)]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
